# kas-dagger-utils
#
# SPDX-License-Identifier: BSD-3-Clause
#
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  # Common -----------------------------------------------------------------------------------------

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.1"
    hooks:
      - id: editorconfig-checker

  # Commits ----------------------------------------------------------------------------------------

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.22.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  # Python -----------------------------------------------------------------------------------------

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.0"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  # JSON, YAML, JavaScript -------------------------------------------------------------------------

  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.0.0-beta.5"
    hooks:
      - id: biome-ci
        additional_dependencies: ["@biomejs/biome"]
